#!/usr/bin/env python3
# =============================================================================
# gen_uvm_reg.py — UVM Register Class Template Generator
# =============================================================================
# Generates a SystemVerilog UVM register class (.sv) from the command line.
# All configure() parameters are left as named placeholders so they can be
# located with a single search for "_PLACEHOLDER*/".
#
# Usage:
#   python3 gen_uvm_reg.py --name <class_name> [options]
#
# Arguments:
#   --name         (required) Register class name, e.g. cfs_algn_reg_ctrl
#   --bits         Register width in bits              (default: 32)
#   --coverage     UVM coverage model                  (default: UVM_NO_COVERAGE)
#   --fields       Number of auto-named fields         (default: 0)
#                  Generates FIELD_1, FIELD_2, ...
#   --field_names  Explicit field names (overrides --fields)
#                  e.g. --field_names RX_FIFO_EMPTY TX_FIFO_FULL
#   --output       Output file path                    (default: <name>.sv)
#
# Examples:
#   python3 gen_uvm_reg.py --name cfs_algn_reg_ctrl --fields 4
#   python3 gen_uvm_reg.py --name cfs_algn_reg_irer \
#       --field_names RX_FIFO_EMPTY RX_FIFO_FULL TX_FIFO_EMPTY TX_FIFO_FULL
#   python3 gen_uvm_reg.py --name my_reg --bits 16 --coverage UVM_CVR_ALL \
#       --field_names STATUS CTRL --output /path/to/my_reg.sv
# =============================================================================
import argparse
import os
from datetime import datetime


CONFIGURE_PARAMS: list[str] = [
    "SIZE",
    "LSB_POS",
    "ACCESS",
    "VOLATILE",
    "RESET",
    "HAS_RESET",
    "IS_RAND",
    "INDIVIDUALLY_ACCESSIBLE",
]


def indent(text: str, spaces: int = 4) -> str:
    pad = " " * spaces
    return "\n".join(pad + line if line else line for line in text.splitlines())


def generate(name: str, bits: int, coverage: str, field_names: list[str]) -> str:
    guard = name.upper() + "_SV"

    field_decls = "\n".join(f"rand uvm_reg_field {f};" for f in field_names)

    create_calls = "\n".join(
        f'{f} = uvm_reg_field::type_id::create("{f}", null, get_full_name());'
        for f in field_names
    )

    def configure_block(fname: str) -> str:
        lines: list[str] = [f".{p.lower()}(/*{fname}_{p}_PLACEHOLDER*/)" for p in CONFIGURE_PARAMS]
        params: str = ",\n".join(lines)
        return (
            f"{fname}.configure(\n"
            f"    this,\n"
            + indent(params, 4)
            + "\n);"
        )

    configure_calls = "\n\n".join(configure_block(f) for f in field_names)

    generated_at: str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    fields_label: str = ", ".join(field_names) if field_names else "(none)"

    decl_block: str = (f"{indent(field_decls, 8)}\n" if field_decls else "")
    create_block: str = (f"{indent(create_calls, 12)}\n" if create_calls else "")
    cfg_block: str = (f"{indent(configure_calls, 12)}\n\n" if configure_calls else "")

    body = f"""\
// =============================================================================
// AUTO-GENERATED by gen_uvm_reg.py — DO NOT EDIT MANUALLY
// Generated : {generated_at}
// Fields    : {fields_label}
// Width     : {bits} bits
// Coverage  : {coverage}
// =============================================================================

`ifndef {guard}

    `define {guard}

    class {name} extends uvm_reg;

{decl_block}        // <<UVM_REG_FIELDS>>

        `uvm_object_utils({name})

        function new(string name = "");
            super.new(name, {bits}, {coverage});
        endfunction

        virtual function void build();
{create_block}            // <<UVM_CREATE_CALLS>>

{cfg_block}            // <<UVM_CONFIGURE_BLOCKS>>

        endfunction
    endclass

`endif
"""
    return body


def main() -> None:
    parser = argparse.ArgumentParser(
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description=(
            "gen_uvm_reg.py — UVM Register Class Template Generator\n"
            "=======================================================\n"
            "Generates a SystemVerilog UVM register class (.sv) file.\n"
            "All configure() parameters are left as named placeholders\n"
            "searchable with: _PLACEHOLDER*/\n"
        ),
        epilog=(
            "Examples:\n"
            "  python3 gen_uvm_reg.py --name cfs_algn_reg_ctrl\n"
            "  python3 gen_uvm_reg.py --name cfs_algn_reg_ctrl --fields 3\n"
            "  python3 gen_uvm_reg.py --name cfs_algn_reg_irer \\\n"
            "      --field_names RX_FIFO_EMPTY RX_FIFO_FULL TX_FIFO_EMPTY TX_FIFO_FULL\n"
            "  python3 gen_uvm_reg.py --name my_reg --bits 16 --coverage UVM_CVR_ALL \\\n"
            "      --field_names STATUS CTRL --output /path/to/my_reg.sv\n"
        ),
    )
    parser.add_argument("--name", required=True, metavar="NAME",
                        help="Register class name, e.g. cfs_algn_reg_ctrl")
    parser.add_argument("--bits", type=int, default=32, metavar="N",
                        help="Register width in bits (default: 32)")
    parser.add_argument("--coverage", default="UVM_NO_COVERAGE", metavar="MODEL",
                        help="UVM coverage model (default: UVM_NO_COVERAGE)")
    parser.add_argument("--fields", type=int, default=0, metavar="N",
                        help="Number of auto-named fields FIELD_1..N (default: 0); ignored if --field_names is given")
    parser.add_argument("--field_names", nargs="+", metavar="NAME",
                        help="Explicit field names, e.g. RX_FIFO_EMPTY TX_FIFO_FULL (overrides --fields)")
    parser.add_argument("--output", default=None, metavar="FILE",
                        help="Output file path (default: <name>.sv next to this script)")

    args = parser.parse_args()

    field_names: list[str] = args.field_names if args.field_names else [f"FIELD_{i}" for i in range(1, args.fields + 1)]

    output_path: str = args.output or os.path.join(
        os.path.dirname(os.path.abspath(__file__)), f"{args.name}.sv"
    )

    content: str = generate(args.name, args.bits, args.coverage, field_names)

    with open(output_path, "w") as f:
        f.write(content)

    print(f"Generated: {output_path}  ({len(field_names)} field(s), {args.bits}-bit, {args.coverage})")


if __name__ == "__main__":
    main()
