#!/usr/bin/env python3
# =============================================================================
# add_uvm_field.py — Add a Field to an Existing UVM Register File
# =============================================================================
# Inserts a new reg field into an existing .sv UVM register class in-place.
# Works best on files generated by gen_uvm_reg.py; warns otherwise.
#
# Usage:
#   python3 add_uvm_field.py --file <FILE> --field_name <NAME> [configure options]
#
# Arguments:
#   --file            (required) Path to the target .sv file
#   --field_name      (required) Name of the new field, e.g. MAX_DROP
#
# Configure options (all optional — omitted args become placeholders):
#   --size                       e.g. 1
#   --lsb_pos                    e.g. 0
#   --access                     e.g. "RW", "W1C", "RO", "WO"
#   --volatile                   e.g. 0
#   --reset                      e.g. "1'b0"
#   --has_reset                  e.g. 1
#   --is_rand                    e.g. 1
#   --individually_accessible    e.g. 0
#
# Examples:
#   python3 add_uvm_field.py --file cfs_algn_reg_ctrl.sv --field_name MAX_DROP \
#       --size 1 --lsb_pos 4 --access '"RW"' --volatile 0 \
#       --reset "1'b0" --has_reset 1 --is_rand 1 --individually_accessible 0
#
#   python3 add_uvm_field.py --file cfs_algn_reg_ctrl.sv --field_name STATUS --size 4
# =============================================================================
import argparse
import re
import sys
from datetime import datetime
from pathlib import Path


AUTOGEN_MARKER: str = "AUTO-GENERATED by gen_uvm_reg.py"
AUTOEDIT_MARKER: str = "AUTO-EDITED by add_uvm_field.py"

TAG_FIELDS: str    = "// <<UVM_REG_FIELDS>>"
TAG_CREATE: str    = "// <<UVM_CREATE_CALLS>>"
TAG_CONFIGURE: str = "// <<UVM_CONFIGURE_BLOCKS>>"

CONFIGURE_PARAMS: list[str] = [
    "SIZE",
    "LSB_POS",
    "ACCESS",
    "VOLATILE",
    "RESET",
    "HAS_RESET",
    "IS_RAND",
    "INDIVIDUALLY_ACCESSIBLE",
]


def indent(text: str, spaces: int = 4) -> str:
    pad = " " * spaces
    return "\n".join(pad + line if line else line for line in text.splitlines())


def get_leading_spaces(line: str) -> int:
    return len(line) - len(line.lstrip(" "))


def build_configure_block(fname: str, param_values: dict[str, str]) -> str:
    lines: list[str] = []
    for p in CONFIGURE_PARAMS:
        value: str = param_values.get(p, f"/*{fname}_{p}_PLACEHOLDER*/")
        lines.append(f".{p.lower()}({value})")
    params: str = ",\n".join(lines)
    return (
        f"{fname}.configure(\n"
        f"    this,\n"
        + indent(params, 4)
        + "\n);"
    )


def find_last_matching_line(lines: list[str], pattern: re.Pattern[str]) -> int:
    result: int = -1
    for i, line in enumerate(lines):
        if pattern.search(line):
            result = i
    return result


def find_last_configure_end(lines: list[str]) -> int:
    """Return index of last standalone ');' line before the last endfunction."""
    endfunction_idx: int = find_last_matching_line(lines, re.compile(r"\bendfunction\b"))

    result: int = -1
    for i in range(endfunction_idx):
        if lines[i].strip() == ");":
            result = i
    return result


def insert_after(lines: list[str], idx: int, new_line: str) -> list[str]:
    return lines[: idx + 1] + [new_line] + lines[idx + 1 :]


def insert_before(lines: list[str], idx: int, new_line: str) -> list[str]:
    return lines[:idx] + [new_line] + lines[idx:]


def find_tag(lines: list[str], tag: str) -> int:
    for i, line in enumerate(lines):
        if tag in line:
            return i
    return -1


CREATE_PATTERN: re.Pattern[str] = re.compile(
    r'^(?P<indent>\s+)(?P<field>\w+)\s*=\s*(?P<rhs>uvm_reg_field::type_id::create\(.+)$'
)


def realign_create_calls(lines: list[str]) -> list[str]:
    """Pad all type_id::create assignment lines so '=' signs are column-aligned."""
    matches: list[tuple[int, str, str]] = []
    for i, line in enumerate(lines):
        m = CREATE_PATTERN.match(line.rstrip('\n'))
        if m:
            matches.append((i, m.group('field'), m.group('indent')))

    if len(matches) < 2:
        return lines

    max_len: int = max(len(field) for _, field, _ in matches)
    result: list[str] = list(lines)
    for i, field, ind in matches:
        rhs: str = CREATE_PATTERN.match(lines[i].rstrip('\n')).group('rhs')  # type: ignore[union-attr]
        result[i] = f"{ind}{field:<{max_len}} = {rhs}\n"
    return result


def update_header(lines: list[str], fname: str) -> list[str]:
    """Replace AUTO-GENERATED/AUTO-EDITED marker, update Last edit timestamp and Fields line."""
    edited_at: str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    edit_line: str = f"// AUTO-EDITED by add_uvm_field.py\n"
    timestamp_line: str = f"// Last edit : {edited_at}\n"
    timestamp_prefix: str = "// Last edit :"
    fields_prefix: str = "// Fields    :"

    result: list[str] = []
    i: int = 0
    while i < len(lines):
        line = lines[i]
        if AUTOGEN_MARKER in line or AUTOEDIT_MARKER in line:
            result.append(edit_line)
            if i + 1 < len(lines) and lines[i + 1].startswith(timestamp_prefix):
                i += 1
            result.append(timestamp_line)
        elif line.startswith(fields_prefix):
            current: str = line.rstrip()
            suffix: str = current[len(fields_prefix):].strip()
            existing: list[str] = [f.strip() for f in suffix.split(",") if f.strip() and f.strip() != "(none)"]
            existing.append(fname)
            result.append(f"{fields_prefix} {', '.join(existing)}\n")
        else:
            result.append(line)
        i += 1
    return result


def main() -> None:
    parser = argparse.ArgumentParser(
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description=(
            "add_uvm_field.py — Add a Field to an Existing UVM Register File\n"
            "=================================================================\n"
            "Inserts a new reg field into an existing .sv UVM register class in-place.\n"
            "Works best on files generated by gen_uvm_reg.py; warns otherwise.\n"
        ),
        epilog=(
            "Examples:\n"
            "  python3 add_uvm_field.py --file cfs_algn_reg_ctrl.sv --field_name MAX_DROP \\\n"
            "      --size 1 --lsb_pos 4 --access '\"RW\"' --volatile 0 \\\n"
            "      --reset \"1'b0\" --has_reset 1 --is_rand 1 --individually_accessible 0\n"
            "\n"
            "  python3 add_uvm_field.py --file cfs_algn_reg_ctrl.sv --field_name STATUS --size 4\n"
        ),
    )
    parser.add_argument("--file", required=True, metavar="FILE",
                        help="Path to the target .sv file")
    parser.add_argument("--field_name", required=True, metavar="NAME",
                        help="Name of the new field, e.g. MAX_DROP")
    configure_help: dict[str, str] = {
        "SIZE":                    'e.g. 1',
        "LSB_POS":                 'e.g. 0',
        "ACCESS":                  'e.g. "RW", "W1C", "RO", "WO"  (omit → placeholder)',
        "VOLATILE":                'e.g. 0  (omit → placeholder)',
        "RESET":                   "e.g. \"1'b0\"  (omit → placeholder)",
        "HAS_RESET":               'e.g. 1  (omit → placeholder)',
        "IS_RAND":                 'e.g. 1  (omit → placeholder)',
        "INDIVIDUALLY_ACCESSIBLE": 'e.g. 0  (omit → placeholder)',
    }
    for p in CONFIGURE_PARAMS:
        parser.add_argument(f"--{p.lower()}", default=None, metavar="VAL",
                            help=configure_help[p])

    args = parser.parse_args()

    file_path: Path = Path(args.file)  # type: ignore[arg-type]
    if not file_path.exists():
        print(f"Error: file '{file_path}' not found.", file=sys.stderr)
        sys.exit(1)

    content: str = file_path.read_text()

    if AUTOGEN_MARKER not in content and AUTOEDIT_MARKER not in content:
        print(
            f"Warning: '{file_path}' does not appear to be generated or edited by the uvm_reg scripts.\n"
            "Modifying it may produce incorrect results."
        )
        answer: str = input("Continue anyway? [y/N] ").strip()
        if answer.lower() != "y":
            print("Aborted.")
            sys.exit(0)

    fname: str = args.field_name
    param_values: dict[str, str] = {
        p: getattr(args, p.lower())
        for p in CONFIGURE_PARAMS
        if getattr(args, p.lower()) is not None
    }

    lines: list[str] = content.splitlines(keepends=True)

    # --- 1. Insert rand declaration ---
    tag_idx: int = find_tag(lines, TAG_FIELDS)
    if tag_idx != -1:
        spaces: int = get_leading_spaces(lines[tag_idx])
        new_decl: str = " " * spaces + f"rand uvm_reg_field {fname};\n"
        lines = insert_before(lines, tag_idx, new_decl)
    else:
        decl_pattern: re.Pattern[str] = re.compile(r"rand\s+uvm_reg_field\s+\w+\s*;")
        decl_idx: int = find_last_matching_line(lines, decl_pattern)
        if decl_idx == -1:
            print("Error: could not find any 'rand uvm_reg_field' declaration or tag.", file=sys.stderr)
            sys.exit(1)
        spaces = get_leading_spaces(lines[decl_idx])
        new_decl = " " * spaces + f"rand uvm_reg_field {fname};\n"
        lines = insert_after(lines, decl_idx, new_decl)

    # --- 2. Insert create call ---
    tag_idx = find_tag(lines, TAG_CREATE)
    if tag_idx != -1:
        spaces = get_leading_spaces(lines[tag_idx])
        new_create: str = " " * spaces + f'{fname} = uvm_reg_field::type_id::create("{fname}", null, get_full_name());\n'
        lines = insert_before(lines, tag_idx, new_create)
    else:
        create_pattern: re.Pattern[str] = re.compile(r"uvm_reg_field::type_id::create\(")
        create_idx: int = find_last_matching_line(lines, create_pattern)
        if create_idx == -1:
            print("Error: could not find any 'type_id::create' call or tag.", file=sys.stderr)
            sys.exit(1)
        spaces = get_leading_spaces(lines[create_idx])
        new_create = " " * spaces + f'{fname} = uvm_reg_field::type_id::create("{fname}", null, get_full_name());\n'
        lines = insert_after(lines, create_idx, new_create)

    lines = realign_create_calls(lines)

    # --- 3. Insert configure block ---
    configure_text: str = build_configure_block(fname, param_values)
    tag_idx = find_tag(lines, TAG_CONFIGURE)
    if tag_idx != -1:
        spaces = get_leading_spaces(lines[tag_idx])
        new_cfg: str = indent(configure_text, spaces) + "\n\n"
        lines = insert_before(lines, tag_idx, new_cfg)
    else:
        cfg_end_idx: int = find_last_configure_end(lines)
        if cfg_end_idx == -1:
            print("Error: could not find any configure block ending or tag.", file=sys.stderr)
            sys.exit(1)
        spaces = get_leading_spaces(lines[cfg_end_idx])
        new_cfg = "\n" + indent(configure_text, spaces) + "\n"
        lines = insert_after(lines, cfg_end_idx, new_cfg)

    lines = update_header(lines, fname)

    file_path.write_text("".join(lines))

    print(f"Added field '{fname}' to '{file_path}'.")
    print(f"Field name: {fname}")
    for p in CONFIGURE_PARAMS:
        value: str = param_values.get(p, f"/*{fname}_{p}_PLACEHOLDER*/")
        print(f"\t{p.lower():<26}: {value}")


if __name__ == "__main__":
    main()
